FROM node:6.9.4-alpine

RUN apk --no-cache add ca-certificates curl make gcc g++ python linux-headers paxctl libgcc libstdc++ gnupg git wget && update-ca-certificates
RUN mkdir -p /opt/yarn && cd /opt/yarn && wget https://yarnpkg.com/latest.tar.gz && tar zxf latest.tar.gz
ENV PATH "/Users/killix/.nvm/versions/node/v6.9.1/bin:/Users/killix/.local/google-cloud-sdk/bin:/usr/local/bin:/Users/killix/.gvm/pkgsets/go1.7.1/global/bin:/Users/killix/.gvm/gos/go1.7.1/bin:/Users/killix/.gvm/pkgsets/go1.7.1/global/overlay/bin:/Users/killix/.gvm/bin:/Users/killix/.gvm/bin:/Users/killix/.cargo/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/killix/bin:/usr/local/Cellar/node/7.3.0/bin:/opt/yarn/dist/bin"

ARG CI_BRANCH
ENV CI_BRANCH $CI_BRANCH

RUN mkdir -p /integrations
WORKDIR /integrations/

COPY ./_tools /integrations/_tools/
RUN chmod +x _tools/scripts/run-install.sh
RUN chmod +x _tools/scripts/run-tests.sh

COPY ./broid-alexa/package.json ./broid-alexa/yarn.lock /integrations/broid-alexa/
COPY ./broid-callr/package.json ./broid-callr/yarn.lock /integrations/broid-callr/
COPY ./broid-discord/package.json ./broid-discord/yarn.lock /integrations/broid-discord/
COPY ./broid-flowdock/package.json ./broid-flowdock/yarn.lock /integrations/broid-flowdock/
COPY ./broid-gitter/package.json ./broid-gitter/yarn.lock /integrations/broid-gitter/
COPY ./broid-google-assistant/package.json ./broid-google-assistant/yarn.lock /integrations/broid-google-assistant/
COPY ./broid-groupme/package.json ./broid-groupme/yarn.lock /integrations/broid-groupme/
COPY ./broid-irc/package.json ./broid-irc/yarn.lock /integrations/broid-irc/
COPY ./broid-kik/package.json ./broid-kik/yarn.lock /integrations/broid-kik/
COPY ./broid-line/package.json ./broid-line/yarn.lock /integrations/broid-line/
COPY ./broid-messenger/package.json ./broid-messenger/yarn.lock /integrations/broid-messenger/
COPY ./broid-ms-teams/package.json ./broid-ms-teams/yarn.lock /integrations/broid-ms-teams/
COPY ./broid-nexmo/package.json ./broid-nexmo/yarn.lock /integrations/broid-nexmo/
COPY ./broid-schemas/package.json ./broid-schemas/yarn.lock /integrations/broid-schemas/
COPY ./broid-skype/package.json ./broid-skype/yarn.lock /integrations/broid-skype/
COPY ./broid-slack/package.json ./broid-slack/yarn.lock /integrations/broid-slack/
COPY ./broid-telegram/package.json ./broid-telegram/yarn.lock /integrations/broid-telegram/
COPY ./broid-twilio/package.json ./broid-twilio/yarn.lock /integrations/broid-twilio/
COPY ./broid-twitter/package.json ./broid-twitter/yarn.lock /integrations/broid-twitter/
COPY ./broid-utils/package.json ./broid-utils/yarn.lock /integrations/broid-utils/
COPY ./broid-viber/package.json ./broid-viber/yarn.lock /integrations/broid-viber/
COPY ./broid-wechat/package.json ./broid-wechat/yarn.lock /integrations/broid-wechat/

COPY ./.git /integrations/.git/

RUN /bin/sh _tools/scripts/run-install.sh

COPY ./broid-alexa/src/core /integrations/broid-alexa/src/core/
COPY ./broid-alexa/src/test /integrations/broid-alexa/src/test/
COPY ./broid-callr/src/core /integrations/broid-callr/src/core/
COPY ./broid-callr/src/test /integrations/broid-callr/src/test/
COPY ./broid-discord/src/core /integrations/broid-discord/src/core/
COPY ./broid-discord/src/test /integrations/broid-discord/src/test/
COPY ./broid-flowdock/src/core /integrations/broid-flowdock/src/core/
COPY ./broid-flowdock/src/test /integrations/broid-flowdock/src/test/
COPY ./broid-gitter/src/core /integrations/broid-gitter/src/core/
COPY ./broid-gitter/src/test /integrations/broid-gitter/src/test/
COPY ./broid-google-assistant/src/core /integrations/broid-google-assistant/src/core/
COPY ./broid-google-assistant/src/test /integrations/broid-google-assistant/src/test/
COPY ./broid-groupme/src/core /integrations/broid-groupme/src/core/
COPY ./broid-groupme/src/test /integrations/broid-groupme/src/test/
COPY ./broid-irc/src/core /integrations/broid-irc/src/core/
COPY ./broid-irc/src/test /integrations/broid-irc/src/test/
COPY ./broid-kik/src/core /integrations/broid-kik/src/core/
COPY ./broid-kik/src/test /integrations/broid-kik/src/test/
COPY ./broid-line/src/core /integrations/broid-line/src/core/
COPY ./broid-line/src/test /integrations/broid-line/src/test/
COPY ./broid-messenger/src/core /integrations/broid-messenger/src/core/
COPY ./broid-messenger/src/test /integrations/broid-messenger/src/test/
COPY ./broid-ms-teams/src/core /integrations/broid-ms-teams/src/core/
COPY ./broid-ms-teams/src/test /integrations/broid-ms-teams/src/test/
COPY ./broid-nexmo/src/core /integrations/broid-nexmo/src/core/
COPY ./broid-nexmo/src/test /integrations/broid-nexmo/src/test/
COPY ./broid-schemas/src/core /integrations/broid-schemas/src/core/
COPY ./broid-schemas/src/test /integrations/broid-schemas/src/test/
COPY ./broid-skype/src/core /integrations/broid-skype/src/core/
COPY ./broid-skype/src/test /integrations/broid-skype/src/test/
COPY ./broid-slack/src/core /integrations/broid-slack/src/core/
COPY ./broid-slack/src/test /integrations/broid-slack/src/test/
COPY ./broid-telegram/src/core /integrations/broid-telegram/src/core/
COPY ./broid-telegram/src/test /integrations/broid-telegram/src/test/
COPY ./broid-twilio/src/core /integrations/broid-twilio/src/core/
COPY ./broid-twilio/src/test /integrations/broid-twilio/src/test/
COPY ./broid-twitter/src/core /integrations/broid-twitter/src/core/
COPY ./broid-twitter/src/test /integrations/broid-twitter/src/test/
COPY ./broid-utils/src/core /integrations/broid-utils/src/core/
COPY ./broid-utils/src/test /integrations/broid-utils/src/test/
COPY ./broid-viber/src/core /integrations/broid-viber/src/core/
COPY ./broid-viber/src/test /integrations/broid-viber/src/test/
COPY ./broid-wechat/src/core /integrations/broid-wechat/src/core/
COPY ./broid-wechat/src/test /integrations/broid-wechat/src/test/

RUN /bin/sh _tools/scripts/run-tests.sh
